# Generated by Django 3.2.2 on 2021-05-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_booksearch_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksearch',
            name='username',
        ),
    ]
